name: Deploy Telegram Bot

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

       # Give permission to gradlew
      - name: Grant Execute Permission
        run: chmod +x gradlew

      # Build Spring Boot Jar
      - name: Build Jar
        run: ./gradlew bootJar

      # Copy jar to VM
      - name: Copy Jar to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/opt/telegram-bot"

      # Restart service safely
      - name: Restart Bot Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            systemctl stop space-events-bot
            mv /opt/telegram-bot/build/libs/*.jar /opt/telegram-bot/space-events-bot.jar
            systemctl start space-events-bot